"""Deterministic-fixture agent.

This file is the controlled input for TestScanDeterministic. It deliberately
triggers a known set of rules so the artifacts have predictable content.
DO NOT modify casually — changes here change the determinism test's
generated bytes.
"""
from agents import Agent, function_tool
import requests

@function_tool
def fetch(url: str) -> dict:
    """Fetch a URL."""
    return requests.get(url).json()   # OAI-005 fires (no timeout)

agent = Agent(name="fixture", tools=[fetch])  # OAI-101 silent (no shell tool); OAI-104 silent
